---
title: "Summary"
output: html_document
date: "2024-12-03"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r set wd}
setwd("C:/Users/LeannaLeverich/The Fertilizer Institute/TFI - Programs/Research/4R/4R Calculator/4R Advocate Case Studies/")
```


```{r packages}
library(readxl)
library(tidyverse)
library(writexl)
```


```{r DE advocate}
advocate = read.csv("2024 Bryant Lowe/Outputs/DE Inputs_sourceMachCosts.csv")

farm = read_excel("2024 Bryant Lowe/DE FarmInfo.xlsx", sheet = 1)

services = read_excel("2024 Bryant Lowe/DE FarmInfo.xlsx", sheet = 2)
```

```{r GA advocate}
advocate = read.csv("2024 Mason Roberts/Outputs/GA Inputs_sourceMachCosts.csv")

farm = read_excel("2024 Mason Roberts/GA FarmInfo.xlsx", sheet = 1)

services = read_excel("2024 Mason Roberts/GA FarmInfo.xlsx", sheet = 2)
```


```{r load nitrous data}
nitrous = read_excel("C:/Users/LeannaLeverich/The Fertilizer Institute/TFI - Programs/Research/4R/4R Calculator/Leanna's Calculator/N2O Emission Factors.xlsx", sheet = 2)
```


# Join Farm Info to advocate info
```{r}
df1 <- advocate %>%
  left_join(farm, by = c("year", "field"))
  
```

# N, P, and K in lbs per ac for each application

```{r}
df2 <- df1 %>%
  mutate(N_lbsAc = Nperc/100 * sourceRate, 
         P_lbsAc = Pperc/100 * sourceRate, 
         K_lbsAc = Kperc/100 * sourceRate)
```

# Nutrient Use Eff Summary 

```{r}
nue <- df2 %>%
  group_by(year, field, crop) %>% 
  summarize(
    TotalN = sum(N_lbsAc, na.rm = TRUE), 
    TotalP = sum(P_lbsAc, na.rm = TRUE),
    TotalK = sum(K_lbsAc, na.rm = TRUE), 
    AvgYield = mean(yield, na.rm = TRUE), 
    NUE_PFP = AvgYield / TotalN, #PFP = (lb grain harvested) / (lb nutrient applied)
    PUE_PFP = AvgYield / TotalP,
    N_removal = mean(case_when(
      crop == "corn" ~ (AvgYield * 56 * 0.0136),
      crop == "cotton" ~ (AvgYield * 0.002083 * 32 ),# 56 lbs/bu and 0.0136 Nconc (%) of grain
      crop == "peanuts" ~ ((AvgYield / 2000) * 70))), # 70 lbs N / ton
    P_removal = mean(case_when(
      crop == "corn" ~ (AvgYield * 0.35), # 0.35 lbs P/bu
      crop == "cotton" ~ (AvgYield * 0.002083 * 14 ),# 56 lbs/bu and 0.0136 Nconc (%) of grain
      crop == "peanuts" ~ ((AvgYield / 2000) * 11))), # 70 lbs N / ton
    NUE_PNB = N_removal/TotalN, # PNB= (lb harvest removal) / (lb applied nutrient)
    PUE_PNB = P_removal/TotalP,
    P_Bal = TotalP - P_removal,# lbs N applied - lb N harvested (N left in soil)
    N_Bal = TotalN - N_removal
    ) 
```

# Cost Summary 
```{r}
# Summarize costs for total costs for machinery and source by year and field
costs <- df2 %>%
  group_by(year, field, level4R, crop) %>%
  summarize(
    totalMachineCost = sum(machineryCosts), 
    totalSourceCost = sum(sourceCost), 
    totalCost = sum(totalCostPerApp), 
    avgYield = mean(yield), 
    Nprice = mean(Nprice),
    Kprice = mean(Kprice),
    Pprice = mean(Pprice),
    Ncost = sum(case_when(
      Nperc != 0 ~ sourceCost,  # Sum sourceCost only when Nperc is not 0
      TRUE ~ 0  # Otherwise, add 0
    ))
  )
# Summary to get total spent on service and subscription by year and field 
costsService <- services %>%
  group_by(year, field) %>%
  summarize(
    totalServiceCost = sum(costDolAc)
  )

# Join machine, source, service, and subscription costs 
costs2 <- costsService %>%
  left_join(costs, by= c("year", "field"))



# Examples of other farm costs to calculate a rough profit 
# Need to add additional crop prices to equation (as needed)
cornPrice = 4.50 # per bu
cottonPrice = 0.73 # per lb
peanutPrice = 0.26 # per lb

# chemical = 100
# land = 300
# seed = 150 
# other = 200 
# otherCosts = chemical + land + seed + other

# Cost summary for each field
totalCosts <- costs2 %>%
  mutate(totalCost = totalCost + totalServiceCost, 
         revenueAc = case_when(
           crop == "cornGrain" ~ avgYield*cornPrice,
           crop == "cotton" ~ avgYield*cottonPrice,
           crop == "peanuts" ~ avgYield*peanutPrice,
           TRUE ~ 0),
         profits = revenueAc - totalCost)

# Compare costs with N rates 
costNUE <- totalCosts %>%
  left_join(nue, by = c("year", "field", "crop"))

```

# CO2 Equivalents 

Basic = N2O * 1.57 * 296
Intermediate = basic - (basic * 0.07) 7% reduction
Advanced = basic - (basic * 0.07) 14% reduction 

Land Resource Region (LRR)

```{r}

# CORN ONLY 

nue2 <- nue %>%
  left_join(farm, by = c("year", "crop", "field"))

nue3 = nue2 %>%
  left_join(nitrous, by = c("LRR", "soilTexture", "crop"))

nue4 = nue3 %>%
  mutate(N_KgHa = TotalN * 1.12085, 
    proportionalDirectKgHa = ((N_KgHa/typicalFertKgNha)*
                              (typicalFluxKgN20ha - zeroFluxKgN20ha)), 
    totalDirectKgHa = zeroFluxKgN20ha + proportionalDirectKgHa, 
    indirectKgHa = N_KgHa*0.0035, 
    total = totalDirectKgHa + indirectKgHa, 
    N2Oequiv=total*(1.57*296), 
    CO2e_buBasic = N2Oequiv/yield,
    CO2e_buInt = CO2e_buBasic - (CO2e_buBasic*0.07),
    CO2e_buAdv = CO2e_buBasic - (CO2e_buBasic*0.14)
  )

n2o <- nue4 %>%
  mutate(CO2equiv = case_when(
    level4R == "Basic" ~  CO2e_buBasic, 
    level4R == "Intermediate" ~  CO2e_buInt, 
    level4R == "Advanced" ~  CO2e_buAdv)) %>%
  select(-CO2e_buBasic, -CO2e_buInt, -CO2e_buAdv)

costNUEco2 <- costNUE %>%
  left_join(n2o %>% select(year, field, CO2equiv), by = c("year", "field"))

```


```{r}
# writing files 
write_xlsx(costNUEco2, "2024 Bryant Lowe/Outputs/Field Summary.xlsx")
# write.csv(nue, file = "2024 Bryant Lowe/Outputs/NUE Summary.csv", row.names = FALSE)
# write.csv(costPerAc, file = "2024 Bryant Lowe/Outputs/Cost Summary.csv", row.names = FALSE)
# write.csv(n2o, file = "2024 Bryant Lowe/Outputs/N2O Summary.csv", row.names = FALSE)
```
```{r}
write_xlsx(costNUEco2, "2024 Mason Roberts/Outputs/Field Summary.xlsx")
# write.csv(nue, file = "2024 Mason Roberts/Outputs/NUE Summary.csv", row.names = FALSE)
# write.csv(costPerAc, file = "2024 Mason Roberts/Outputs/Cost Summary.csv", row.names = FALSE)
# write.csv(n2o, file = "2024 Mason Roberts/Outputs/N2O Summary.csv", row.names = FALSE)
```


